import { z } from 'zod';
import type {
  PermissionContract,
  PermissionGroupContract,
} from './permissions';

export const CORE_PERMISSION_KEYS = [
  'core:access',
  'settings:access',
  'users:access',
  'users:read',
  'users:create',
  'users:update',
  'access-control:access',
  'access-control:read',
  'access-control:manage',
  'tasks:access',
  'tasks:read',
] as const;

export const CorePermissionKeySchema = z.enum(CORE_PERMISSION_KEYS);

export const ACCESS_CONTROL_PERMISSION_GROUPS = [
  {
    id: 'group.core',
    key: 'core',
    label: 'Core',
    description: 'Core shell access and baseline authenticated entrypoints.',
    sortOrder: 10,
  },
  {
    id: 'group.settings',
    key: 'settings',
    label: 'Settings',
    description: 'Template settings and configuration visibility.',
    sortOrder: 20,
  },
  {
    id: 'group.users',
    key: 'users',
    label: 'Users',
    description: 'Authenticated user directory and profile visibility.',
    sortOrder: 30,
  },
  {
    id: 'group.access-control',
    key: 'access-control',
    label: 'Access Control',
    description: 'Roles, permissions and access overview.',
    sortOrder: 40,
  },
  {
    id: 'group.tasks',
    key: 'tasks',
    label: 'Tasks',
    description: 'Example tasks module visibility.',
    sortOrder: 50,
  },
] as const satisfies readonly PermissionGroupContract[];

export const ACCESS_CONTROL_CORE_PERMISSIONS = [
  {
    id: 'core.access',
    key: 'core:access',
    moduleId: 'core',
    groupId: 'group.core',
    group: ACCESS_CONTROL_PERMISSION_GROUPS[0],
    action: 'access',
    label: 'Access Core',
    description: 'Allows access to the Core landing module.',
  },
  {
    id: 'settings.access',
    key: 'settings:access',
    moduleId: 'settings',
    groupId: 'group.settings',
    group: ACCESS_CONTROL_PERMISSION_GROUPS[1],
    action: 'access',
    label: 'Access Settings',
    description: 'Allows access to the Settings module.',
  },
  {
    id: 'users.access',
    key: 'users:access',
    moduleId: 'users',
    groupId: 'group.users',
    group: ACCESS_CONTROL_PERMISSION_GROUPS[2],
    action: 'access',
    label: 'Access Users',
    description: 'Allows access to the Users module.',
  },
  {
    id: 'users.read',
    key: 'users:read',
    moduleId: 'users',
    groupId: 'group.users',
    group: ACCESS_CONTROL_PERMISSION_GROUPS[2],
    action: 'read',
    label: 'Read Users',
    description: 'Allows reading authenticated user profiles.',
  },
  {
    id: 'users.create',
    key: 'users:create',
    moduleId: 'users',
    groupId: 'group.users',
    group: ACCESS_CONTROL_PERMISSION_GROUPS[2],
    action: 'create',
    label: 'Create Users',
    description: 'Allows provisioning and reactivating users.',
  },
  {
    id: 'users.update',
    key: 'users:update',
    moduleId: 'users',
    groupId: 'group.users',
    group: ACCESS_CONTROL_PERMISSION_GROUPS[2],
    action: 'update',
    label: 'Update Users',
    description: 'Allows enabling or disabling users.',
  },
  {
    id: 'access-control.access',
    key: 'access-control:access',
    moduleId: 'access-control',
    groupId: 'group.access-control',
    group: ACCESS_CONTROL_PERMISSION_GROUPS[3],
    action: 'access',
    label: 'Access Control Module',
    description: 'Allows access to the access-control module.',
  },
  {
    id: 'access-control.read',
    key: 'access-control:read',
    moduleId: 'access-control',
    groupId: 'group.access-control',
    group: ACCESS_CONTROL_PERMISSION_GROUPS[3],
    action: 'read',
    label: 'Read Access Control',
    description: 'Allows reading the permission catalog.',
  },
  {
    id: 'access-control.manage',
    key: 'access-control:manage',
    moduleId: 'access-control',
    groupId: 'group.access-control',
    group: ACCESS_CONTROL_PERMISSION_GROUPS[3],
    action: 'manage',
    label: 'Manage Access Control',
    description: 'Allows managing future roles and permission assignments.',
  },
  {
    id: 'tasks.access',
    key: 'tasks:access',
    moduleId: 'tasks',
    groupId: 'group.tasks',
    group: ACCESS_CONTROL_PERMISSION_GROUPS[4],
    action: 'access',
    label: 'Access Tasks',
    description: 'Allows access to the example Tasks module.',
  },
  {
    id: 'tasks.read',
    key: 'tasks:read',
    moduleId: 'tasks',
    groupId: 'group.tasks',
    group: ACCESS_CONTROL_PERMISSION_GROUPS[4],
    action: 'read',
    label: 'Read Tasks',
    description: 'Allows reading example tasks.',
  },
] as const satisfies readonly PermissionContract[];

export type CorePermissionKeyContract = z.infer<typeof CorePermissionKeySchema>;
